# Generated by Django 5.0.6 on 2024-06-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="заголовок")),
                ("slug", models.CharField(max_length=100, verbose_name="slug")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="содержимое"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="img_publication",
                        verbose_name="превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="дата создания"),
                ),
                (
                    "publication_activ",
                    models.BooleanField(
                        default=True, verbose_name="признак публикации"
                    ),
                ),
                (
                    "counter",
                    models.IntegerField(
                        default=0, verbose_name="количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
    ]
