# Generated by Django 5.0.6 on 2024-06-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoryMailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_date", models.DateField(verbose_name="дата последней попытки")),
                ("status", models.BooleanField(verbose_name="статус успешно/нет")),
                ("response", models.CharField(verbose_name="ответ почтового сервера")),
            ],
            options={
                "verbose_name": "История рассылки",
                "verbose_name_plural": "Истории рассылок",
            },
        ),
        migrations.CreateModel(
            name="MailingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=100, verbose_name="тема письма")),
                ("body", models.CharField(max_length=150, verbose_name="тело письма")),
            ],
            options={
                "verbose_name": "Сообщение рассылки",
                "verbose_name_plural": "Сообщения рассылки",
            },
        ),
        migrations.CreateModel(
            name="RecipientClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="ф.и.о")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="комментарий"),
                ),
            ],
            options={
                "verbose_name": "Клиент получатель",
                "verbose_name_plural": "Клиенты получатели",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_date",
                    models.DateField(
                        verbose_name="дата первой отправки. Формат: 2024-06-13"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("раз в день", "день"),
                            ("раз в неделю", "неделя"),
                            ("раз в месяц", "месяц"),
                        ],
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "check_periodicity",
                    models.IntegerField(
                        default="0", verbose_name="дней до следующей отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("завершена", "завершена"),
                            ("создана", "создана"),
                            ("запущена", "запущена"),
                        ],
                        default="создана",
                        null=True,
                        verbose_name="статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mailings.mailingmessage",
                        verbose_name="сообщение",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        to="mailings.recipientclient", verbose_name="клиенты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
